Application/WebAppLab2Turma20161/ViewModels/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebAppLab2Turma20161.Models;

namespace WebAppLab2Turma20161.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<Carrinho> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

Application/WebAppLab2Turma20161/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppLab2Turma20161.Models;

namespace WebAppLab2Turma20161.Controllers
{

    [Authorize]
    public class CheckoutController : Controller
    {

        private ContextoEF db = new ContextoEF();
        const String PromoCode = "FREE";
        public ActionResult AddressAndPayment()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new Pedido();

            TryUpdateModel(order);

            try
            {
                if (string.Equals(values["PromoCode"], PromoCode, StringComparison.OrdinalIgnoreCase) == false)
                {
                    return View(order);
                }
                else
                {
                    order.NomeUsuarioCliente = User.Identity.Name;
                    order.DataRegistro = DateTime.Now;

                    db.Pedidos.Add(order);
                    db.SaveChanges();

                    var cart = CarrinhoCompras.ObterCarrinhoAtual(this.HttpContext);
                    cart.CriarPedido(order);

                    db.SaveChanges();//we have received the total amount lets update it
                    ViewBag.TotalPedido = order.Total;
                    return RedirectToAction("Complete", new {id = order.PedidoId});
                }
            }
            catch(Exception ex)
            {
                ex.InnerException.ToString();
                return View(order);
            }
        }

        public ActionResult Complete(int id)
        {
            bool isValid = db.Pedidos.Any(
                o => o.PedidoId == id &&
                     o.NomeUsuarioCliente == User.Identity.Name
                );

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

Application/WebAppLab2Turma20161/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using WebAppLab2Turma20161.Models;
using WebAppLab2Turma20161.ViewModels;

namespace WebAppLab2Turma20161.Controllers
{
    public class ShoppingCartController : Controller
    {
        private ContextoEF db = new ContextoEF();

        public ActionResult Index()
        {
            var cart = CarrinhoCompras.ObterCarrinhoAtual(this.HttpContext);

            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.ObterItensCarrinho(),
                CartTotal = cart.ObterTotal()
            };

            return View(viewModel);
        }

        public ActionResult AddToCart(int id)
        {
            var addedProduct = db.Produtos.Single(product => product.ProdutoId == id);

            var cart = CarrinhoCompras.ObterCarrinhoAtual(this.HttpContext);

            cart.AdicionarNoCarrinho(addedProduct);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var cart = CarrinhoCompras.ObterCarrinhoAtual(this.HttpContext);

            string productName = db.Carrinhos.FirstOrDefault(item => item.ProdutoId == id).Produto.Nome;

            int itemCount = cart.RemoverItemDoCarrinho(id);

            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(productName) + " foi removido do seu carrinho de compras",
                CartTotal = cart.ObterTotal(),
                CartCount = cart.ObterTotalItens(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = CarrinhoCompras.ObterCarrinhoAtual(this.HttpContext);

            ViewData["CartCount"] = cart.ObterTotalItens();
            return PartialView("CartSummary");
        }

    }
}

Application/WebAppLab2Turma20161/Views/ShoppingCart/CartSummary.cshtml
@Html.ActionLink("Meu Carrinho (" + ViewData["CartCount"] + ")","Index","ShoppingCart",new { id = "cart-status" })

Application/WebAppLab2Turma20161/Views/ShoppingCart/Index.cshtml
@using System.Diagnostics.Eventing.Reader
@using System.Globalization
@model WebAppLab2Turma20161.ViewModels.ShoppingCartViewModel

@{
    ViewBag.Title = "Meu Carrinho de Compras";
    CultureInfo us = new CultureInfo("pt-br");
}


<h3 class="text-center">
     <span><img src="~/Content/Images/shoping_cart.png" />Seu carrinho de compras:</span>
</h3>

<div id="update-message" class="text-info">
</div>
@if (Model.CartItems.Count==0)
{
    <a class="btn-danger" href="~/StoreFront/Index/1">Carrinho vazio... continuar comprando ---></a>
}
else
{
    <table class="table table-responsive table-bordered table-striped">
        <tr>
            <th>
                Produto
            </th>
            <th>
               Preço(Unidade)
            </th>
            <th>
                Quantidade
            </th>
            <th>Sub-total</th>
            <th></th>
        </tr>
        @foreach (var item in Model.CartItems)
        {
            <tr id="row-@item.ProdutoId">
                <td>
                    @Html.ActionLink(item.Produto.Nome, "Index", "Home", new {id = item.ProdutoId}, null)
                </td>
                <td>
                    @item.Produto.Preco
                </td>
                <td id="item-count-@item.ProdutoId">
                    @item.TotalItens
                </td>
                <td>
                    @((item.Produto.Preco * item.TotalItens).ToString("c",us))
                </td>
                <td>
                    <a href="" class="RemoveLink" data-id="@item.ProdutoId">
                        Remover do carrinho
                    </a>
                </td>
            </tr>
        }
        <tr>
            <td>
                Total
            </td>
            <td></td>
            <td></td>
            <td id="cart-total" class="text-success">
                <b>@Model.CartTotal.ToString("C",us)</b>
            </td>
        </tr>
    </table>

    <p class="button">
        <a href="~/StoreFront/Index/1">Continuar comprando >> </a>
    </p>
    <p class="button">
        @Html.ActionLink("Finalizar pedido (Checkout) >> ", "AddressAndPayment", "Checkout")
    </p>
}