Application/WebAppLab2Turma20161/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppLab2Turma20161.Models
{
    [Bind(Exclude = "PedidoId")]
    public class Pedido
    {
        [ScaffoldColumn(false)]
        [Display(Name = "Id do Pedido")]
        public int PedidoId { get; set; }

        [Required(ErrorMessage = "{0} obrigatório")]
        [DisplayName("Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "{0} obrigatório")]
        [DisplayName("Sobrenome")]
        public string Sobrenome { get; set; }

        [Required(ErrorMessage = "{0} obrigatório")]
        public string Endereco { get; set; }

        [Required(ErrorMessage = "{0} obrigatório")]
        public string Cidade { get; set; }

        [Required(ErrorMessage = "{0} obritatório")]
        public string Estado { get; set; }

        [Required(ErrorMessage = "{0} obrigatório")]
        [DisplayName("CEP")]
        public string CEP { get; set; }

        [Required(ErrorMessage = "{0} obrigatório")]
        [DisplayName("País")]
        public string Pais { get; set; }

        [Required(ErrorMessage = "{0} obrigatório")]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "{0} obrigatório")]
        [DisplayName("E-mail do Checkout")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}",
            ErrorMessage = "E-mail inválido.")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
     
        [ScaffoldColumn(false)]
        [Column(TypeName = "datetime2")]
        [Display(Name = "Data do Pedido")]
        public DateTime DataRegistro { get; set; }

        public int? ClienteID { get; set; }
        public virtual Cliente Cliente { get; set; }

        [Display(Name = "Data do Envio")]
        public DateTime? DataEnvio { get; set; }

        [Display(Name = "Data da Entrega")]
        public DateTime? DataEntrega { get; set; }

        
        [ScaffoldColumn(false)]
        public Decimal Total { get; set; }

        [Display(Name = "E-mail de Cadastro")]
        [DataType(DataType.EmailAddress)]
        [ScaffoldColumn(false)]
        public string NomeUsuarioCliente { get; set; }

    }
}

Application/WebAppLab2Turma20161/Areas/Administracao/Controllers/PedidoController.cs
using PagedList;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppLab2Turma20161.Models;

namespace Areas.Administracao.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class PedidoController : Controller
    {
        private ContextoEF db = new ContextoEF();


        public ActionResult GerarPDF(int id)
        {
            var modelo = db.Pedidos.Find(id);

            var pdf = new ViewAsPdf
            {
                ViewName = "DetailsParaImpressao",
                Model = modelo
            };

            return pdf;
        }

        public ActionResult ConsultarCliente(int? pagina, string nomeCliente = null)
        {
            int tamanhoPagina = 3;
            int numeroPagina = pagina ?? 1;
            var cliente = new Object();

            if (!String.IsNullOrEmpty(nomeCliente))
            {
                cliente = db.Pedidos
                    .Where(c => c.Nome.ToUpper().Contains(nomeCliente.ToUpper()))
                    .OrderBy(c => c.Nome)
                    .ToPagedList(numeroPagina, tamanhoPagina);
            }
            else
            {
                cliente = db.Pedidos.OrderBy(p => p.Nome).ToPagedList(numeroPagina, tamanhoPagina);
            }
            return View("Index", cliente);
        }
    

        // GET: Pedido
        public ActionResult Index(string ordenacao, int? pagina)
        {
            ViewBag.OrdenacaoAtual = ordenacao;
            ViewBag.NomeParam = String.IsNullOrEmpty(ordenacao) ? "Nome_desc" : "";
            ViewBag.DataPedidoParam = ordenacao == "DataPedido" ? "DataPedido_desc" : "DataPedido";
            ViewBag.DataEnvioParam = ordenacao == "DataEnvio" ? "DataEnvio_desc" : "DataEnvio";
            ViewBag.DataEntregaParam = ordenacao == "DataEntrega" ? "DataEntrega_desc" : "DataEntrega";

            var pedidos = from c in db.Pedidos select c;

            int tamanhoPagina = 5;
            int numeroPagina = pagina ?? 1;

            switch (ordenacao)
            {
                case "Nome_desc":
                    pedidos = pedidos.OrderByDescending(s => s.Cliente.Nome);
                    break;
                case "DataPedido":
                    pedidos = pedidos.OrderBy(s => s.DataRegistro);
                    break;
                case "DataPedido_desc":
                    pedidos = pedidos.OrderByDescending(s => s.DataRegistro);
                    break;
                case "DataEenvio":
                    pedidos = pedidos.OrderBy(s => s.DataEnvio);
                    break;
                case "DataEnvio_desc":
                    pedidos = pedidos.OrderByDescending(s => s.DataEnvio);
                    break;
                case "DataEntrega":
                    pedidos = pedidos.OrderBy(s => s.DataEntrega);
                    break;
                case "DataEntrega_desc":
                    pedidos = pedidos.OrderByDescending(s => s.DataEntrega);
                    break;
                default:
                    pedidos = pedidos.OrderBy(s => s.Cliente.Nome);
                    break;
            }



            return View(pedidos.ToPagedList(numeroPagina, tamanhoPagina));
        }

        // GET: Pedido/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // GET: Pedido/Create
        public ActionResult Create()
        {
            ViewBag.ClienteID = new SelectList(db.Clientes, "ClienteId", "Nome");
            return View();
        }

        // POST: Pedido/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                db.Pedidos.Add(pedido);
                db.SaveChanges();
                TempData["Mensagem"] = "Pedido cadastrado com sucesso!";
                return RedirectToAction("Index");
            }

            ViewBag.ClienteID = new SelectList(db.Clientes, "ClienteId", "Nome", pedido.ClienteID);
            return View(pedido);
        }

        // GET: Pedido/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClienteID = new SelectList(db.Clientes, "ClienteId", "Nome", pedido.ClienteID);
            return View(pedido);
        }

        // POST: Pedido/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pedido).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Mensagem"] = "Pedido atualizado com sucesso!";
                return RedirectToAction("Index");
            }
            ViewBag.ClienteID = new SelectList(db.Clientes, "ClienteId", "Nome", pedido.ClienteID);
            return View(pedido);
        }

        // GET: Pedido/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // POST: Pedido/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pedido pedido = db.Pedidos.Find(id);
            db.Pedidos.Remove(pedido);
            db.SaveChanges();
            TempData["Mensagem"] = "Pedido excluído com sucesso!";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Application/WebAppLab2Turma20161/Areas/Administracao/Views/Pedido/Create.cshtml
@model WebAppLab2Turma20161.Models.Pedido

@{
    ViewBag.Title = "Pedido - Cadastro";
    Layout = "~/Views/Shared/_LayoutPageInterno.cshtml";
}

<div class="modal-dialog">
    <div class="modal-content">


        @using (Html.BeginForm())
        {

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Cadastro de Pedido</h4>
            </div>

            @Html.AntiForgeryToken()

            <div class="modal-body">
                <div class="form-horizontal">

                 
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.ClienteID, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("ClienteID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ClienteID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DataRegistro, "Data do Pedido", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DataRegistro, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DataRegistro, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DataEnvio, "Data do Envio", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DataEnvio, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DataEnvio, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DataEntrega, "Data de Entrega", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DataEntrega, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DataEntrega, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    </div>

                <div class="modal-footer">
                    <input type="submit" value="Cadastrar" class="btn btn-primary" />
                    <input type="button" value="Cancelar" class="btn btn-default" data-dismiss="modal" />
                </div>
                </div>
                }

             

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/jquerymask")

                    <script>
                        $(document).ready(function () {
                            $("#DataPedido").datepicker().mask("99/99/9999", { placeholder: "dd/mm/aaaa" });
                            $("#DataEnvio").datepicker().mask("99/99/9999", { placeholder: "dd/mm/aaaa" });
                            $("#DataEntrega").datepicker().mask("99/99/9999", { placeholder: "dd/mm/aaaa" });

                        });
                    </script>
                }
            </div>
</div>

Application/WebAppLab2Turma20161/Areas/Administracao/Views/Pedido/Delete.cshtml
@model WebAppLab2Turma20161.Models.Pedido


@{
    ViewBag.Title = "Delete";
    Layout = null;
}

<div class="modal-dialog">
    <div class="modal-content">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
           
            <h2>Você tem certeza que deseja excluir esse registro?</h2>
        </div>

        <div class="modal-body">

          
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nome)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nome)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DataRegistro)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DataRegistro)
                </dd>


</dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="modal-footer">
                    <input type="submit" value="Confirmar" class="btn btn-primary" />
                    <input type="button" value="Cancelar" class="btn btn-default" data-dismiss="modal" />
                </div>
            }
        </div>

    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

Application/WebAppLab2Turma20161/Areas/Administracao/Views/Pedido/Details.cshtml
@model WebAppLab2Turma20161.Models.Pedido

@{
    ViewBag.Title = "Details";
    Layout = null;
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Detalhes do Pedido</h4>
        </div>
        <div class="modal-body">


            <p>@Html.DisplayNameFor(model => model.PedidoId) : @Html.DisplayFor(model => model.PedidoId)</p>
            <p>@Html.DisplayNameFor(model => model.Nome) : @Html.DisplayFor(model => model.Nome)</p>
            <p>@Html.DisplayNameFor(model => model.Sobrenome) : @Html.DisplayFor(model => model.Sobrenome)</p>
            <p>@Html.DisplayNameFor(model => model.Endereco) : @Html.DisplayFor(model => model.Endereco)</p>
            <p>@Html.DisplayNameFor(model => model.Cidade) : @Html.DisplayFor(model => model.Cidade)</p>
            <p>@Html.DisplayNameFor(model => model.Estado) : @Html.DisplayFor(model => model.Estado)</p>
            <p>@Html.DisplayNameFor(model => model.CEP) : @Html.DisplayFor(model => model.CEP)</p>
            <p>@Html.DisplayNameFor(model => model.Pais) : @Html.DisplayFor(model => model.Pais)</p>
            <p>@Html.DisplayNameFor(model => model.Telefone) : @Html.DisplayFor(model => model.Telefone)</p>
            <p>@Html.DisplayNameFor(model => model.NomeUsuarioCliente) : @Html.DisplayFor(model => model.NomeUsuarioCliente)</p>
            <p>@Html.DisplayNameFor(model => model.Email) : @Html.DisplayFor(model => model.Email)</p>
            <p>@Html.DisplayNameFor(model => model.Total) : R$@Html.DisplayFor(model => model.Total)</p>
            <p>@Html.DisplayNameFor(model => model.DataRegistro) : @Html.DisplayFor(model => model.DataRegistro)</p>
           
            
            <div class="text-right"><a href="~/Administracao/Pedido/GerarPDF/@Model.PedidoId" class="btn btn-danger">Gerar Relatório em PDF</a></div>

        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

Application/WebAppLab2Turma20161/Areas/Administracao/Views/Pedido/DetailsParaImpressao.cshtml
@model WebAppLab2Turma20161.Models.Pedido

@{
    ViewBag.Title = "Relatório do Pedido";
    Layout = "~/Views/Shared/_LayoutParaImpressao.cshtml";
}
<h2 class="text-center"><img src="~/Content/Images/logo.png" alt="" /></h2>
<h2 class="text-center"> <b>Informações do Pedido</b></h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <h4>
            <dl class="dl-horizontal">
                
                <p>@Html.DisplayNameFor(model => model.PedidoId) : @Html.DisplayFor(model => model.PedidoId)</p>
                <p>@Html.DisplayNameFor(model => model.Nome) : @Html.DisplayFor(model => model.Nome)</p>
                <p>@Html.DisplayNameFor(model => model.Sobrenome) : @Html.DisplayFor(model => model.Sobrenome)</p>
                <p>@Html.DisplayNameFor(model => model.Endereco) : @Html.DisplayFor(model => model.Endereco)</p>
                <p>@Html.DisplayNameFor(model => model.Cidade) : @Html.DisplayFor(model => model.Cidade)</p>
                <p>@Html.DisplayNameFor(model => model.Estado) : @Html.DisplayFor(model => model.Estado)</p>
                <p>@Html.DisplayNameFor(model => model.CEP) : @Html.DisplayFor(model => model.CEP)</p>
                <p>@Html.DisplayNameFor(model => model.Pais) : @Html.DisplayFor(model => model.Pais)</p>
                <p>@Html.DisplayNameFor(model => model.Telefone) : @Html.DisplayFor(model => model.Telefone)</p>
                <p>@Html.DisplayNameFor(model => model.NomeUsuarioCliente) : @Html.DisplayFor(model => model.NomeUsuarioCliente)</p>
                <p>@Html.DisplayNameFor(model => model.Email) : @Html.DisplayFor(model => model.Email)</p>
                <p>@Html.DisplayNameFor(model => model.Total) : R$@Html.DisplayFor(model => model.Total)</p>
                <p>@Html.DisplayNameFor(model => model.DataRegistro) : @Html.DisplayFor(model => model.DataRegistro)</p>
</h4>    
       
    </dl>
</div>

Application/WebAppLab2Turma20161/Areas/Administracao/Views/Pedido/Edit.cshtml
@model WebAppLab2Turma20161.Models.Pedido

@{
    ViewBag.Title = "Pedido - Edital";
    Layout = "~/Views/Shared/_LayoutPageInterno.cshtml";
}

<div class="modal-dialog">
    <div class="modal-content">


      @using (Html.BeginForm("Edit", "Pedido", FormMethod.Post))
      {

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Edital de Pedido</h4>
        </div>
            @Html.AntiForgeryToken()

        <div class="modal-body">
            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.PedidoId)

                <div class="form-group">
                    @Html.LabelFor(model => model.ClienteID, "Nome do Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ClienteID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ClienteID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DataRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DataRegistro, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DataRegistro, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DataEnvio, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DataEnvio, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DataEnvio, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DataEntrega, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DataEntrega, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DataEntrega, "", new { @class = "text-danger" })
                    </div>
                </div>
                </div>

            <div class="modal-footer">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <input type="button" value="Cancelar" class="btn btn-default" data-dismiss="modal" />
            </div>
            </div>
            }

         

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/jquerymask")
                <script>
                    $(document).ready(function () {
                        $("#DataPedido").datepicker().mask("99/99/9999", { placeholder: "dd/mm/aaaa" });
                        $("#DataEnvio").datepicker().mask("99/99/9999", { placeholder: "dd/mm/aaaa" });
                        $("#DataEntrega").datepicker().mask("99/99/9999", { placeholder: "dd/mm/aaaa" });

                    });
                </script>
            }
        </div>
</div>

Application/WebAppLab2Turma20161/Areas/Administracao/Views/Pedido/Index.cshtml
@model PagedList.IPagedList<WebAppLab2Turma20161.Models.Pedido>
@using PagedList
@using PagedList.Mvc 
@{
    ViewBag.Title = "Pedidos";
}

<h2 class="text-center"><b>Lista de Pedidos</b> </h2>

<div class="modal" id="modal">

</div>

<form class="text-right" method="get" action="/Administracao/Pedido/ConsultarCliente">
    <p>
        <input type="search" placeholder="Pesquisar Cliente" name="nomeCliente" />
        <button type="submit" value="Pesquisar" class="btn btn-info btn-circle"title="Pesquisar"><i class="glyphicon glyphicon-search"></i></button>
        <button type="submit" value="Mostrar Todos" class="btn btn-warning btn-circle"title="Mostrar Todos"><i class="glyphicon glyphicon-remove"></i></button>

    </p>
</form>
@*<button class="btn btn-default create"><i class="glyphicon glyphicon-new-window"></i>Novo Pedido</button>

@if (TempData["Mensagem"] != null)
{

    <p class="alert-success">@TempData["Mensagem"]</p>

}*@

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Nome do Cliente", "Index", new { ordenacao = ViewBag.NomeParam })
        </th>
        <th>
            @Html.ActionLink("Data do Pedido", "Index", new { ordenacao = ViewBag.DataPedidoParam })
        </th>
        
        @*<th>
            @Html.ActionLink("Data do Envio", "Index", new { ordenacao = ViewBag.DataEnvioParam })
        </th>
        <th>
            @Html.ActionLink("Data de Entrega", "Index", new { ordenacao = ViewBag.DataEntregaParam })
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataRegistro)
        </td>
       
     
        <td>
            @*@Html.ActionLink("Editar", "Edit", new { id=item.PedidoId }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.PedidoId }) |
            @Html.ActionLink("Excluir", "Delete", new { id=item.PedidoId })*@
            <button class="btn btn-default details" data-id="@item.PedidoId" title="Detalhes do Pedido"><i class="glyphicon glyphicon-file"></i></button>
            
           @* <button class="btn btn-danger delete" data-id="@item.PedidoId"><i class="glyphicon glyphicon-trash"></i></button>*@
            @*<button class="btn btn-primary edit" data-id="@item.PedidoId"><i class="glyphicon glyphicon-edit"></i></button>*@
        </td>
    </tr>
}

</table>

@section scripts{

    <script>
        $(function () {

            $(".details").click(function () {
                var id = $(this).attr("data-id");
                $("#modal").load("/Administracao/Pedido/Details?id=" + id, function () {
                    $("#modal").modal();
                })
            });

            $(".edit").click(function () {
                var id = $(this).attr("data-id");
                $("#modal").load("/Administracao/Pedido/Edit?id=" + id, function () {
                    $("#modal").modal();
                })
            });

            $(".delete").click(function () {
                var id = $(this).attr("data-id");
                $("#modal").load("/Administracao/Pedido/Delete?id=" + id, function () {
                    $("#modal").modal();
                })
            });

            $(".create").click(function () {
                $("#modal").load("/Administracao/Pedido/Create", function () {
                    $("#modal").modal();
                 })

            });

        })


    </script>
}

Página @Model.PageNumber de @Model.PageCount
@Html.PagedListPager(Model, Page => Url.Action("Index", new { pagina = Page, ordenacao = ViewBag.OrdenacaoAtual }))